specVersion: 0.0.5
description: Pangolin Near
repository: https://github.com/antiyro/pangolinNear.git
schema:
  file: ../schema.graphql
dataSources:
  - kind: near
    name: receipts
    network: near-mainnet
    source:
      startBlock: {{ contracts.exchange.startBlock }}
      account:  '{{ contracts.exchange.account }}'
    mapping:
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      file: ../src/mapping.ts
      entities:
        - Account
        - Swap
        - AddLiquidity
        - Transaction
        - Pair
        - Token
        - LiquidityPosition
      receiptHandlers:
        - handler: handleReceipt

