[general]
#https://github.com/graphprotocol/graph-node/blob/master/docs/config.md
[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.avalanche]
shard = "primary"
provider = [
    { label = "avalanche1", url = "$SINGLE_RPC_ENDPOINT",features = []}
]
[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]