name: EVM Governance publish
env:
  CI: true
on:
  push:
    branches:
      - dev
    paths:
      - subgraphs/evm/governance
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Configure Git
        run: |
          git config --global user.name 'Pangolin'
          git config --global user.email 'pangolindex@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org/'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn --frozen-lockfile
        env:
          CI: true
      - run: ls subgraphs/evm
        env:
          CI: true
      - name: Avalanche deployment
        run: yarn deploySubgraph --network avalanche --subgraph governance -e prod --user pangolindex -v $(git rev-parse --verify HEAD --short) -t $GRAPH_AUTH_TOKEN
        env:
          GRAPH_AUTH_TOKEN: ${{ secrets.GRAPH_AUTH_TOKEN }}
